// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// src/app/layout.tsx
import './globals.css'
import { ReactNode } from 'react'
import Link from 'next/link'

export const metadata = {
  title: 'Chemistry Simulations',
  description: 'Various chemical simulation games built with Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja">
      <body className="min-h-screen bg-gradient-to-br from-indigo-800 via-purple-700 to-pink-500 text-gray-100">
        {/* ヘッダー */}
        <header className="backdrop-blur-md bg-white/10 py-4 px-8">
          <nav className="max-w-5xl mx-auto flex items-center justify-between">
            <Link href="/">
              <h1 className="text-2xl font-bold hover:opacity-80 transition">
                🔬 ChemLab
              </h1>
            </Link>
            <ul className="flex space-x-4">
              <li>
                <Link
                  href="/element-simulator"
                  className="hover:underline"
                >
                  Element Simulator
                </Link>
              </li>
              {/* 必要に応じてリンクを追加 */}
            </ul>
          </nav>
        </header>

        {/* メインコンテンツ */}
        <main className="max-w-5xl mx-auto py-8 px-4">
          {children}
        </main>

        {/* フッター */}
        <footer className="backdrop-blur-md bg-white/10 py-4 px-8 mt-8">
          <div className="max-w-5xl mx-auto text-center">
            <p className="text-sm">
              &copy; 2025 ChemLab. All Rights Reserved.
            </p>
          </div>
        </footer>
      </body>
    </html>
  )
}
